"""initial schema

Revision ID: 7618688be7dc
Revises: 
Create Date: 2026-09-03 09:33:02.704933
"""
from alembic import op
import sqlalchemy as sa


revision = '7618688be7dc'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organisations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('type', sa.Enum('institution', 'publisher', 'individual', name='orgtype'), nullable=False),
    sa.Column('plan', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('kind', sa.Enum('submission', 'source', 'web', name='dockind'), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('source_url', sa.String(length=1000), nullable=True),
    sa.Column('storage_key', sa.String(length=500), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_hash', sa.String(length=64), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('indexed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_documents_org_kind', 'documents', ['org_id', 'kind'], unique=False)
    op.create_index('ix_documents_text_hash', 'documents', ['text_hash'], unique=False)
    op.create_table('memberships',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('owner', 'admin', 'member', 'viewer', name='memberrole'), nullable=False),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'org_id')
    )
    op.create_table('checks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_id', sa.Integer(), nullable=True),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('queued', 'running', 'done', 'failed', name='checkstatus'), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('similarity_pct', sa.Float(), nullable=True),
    sa.Column('ai_prob', sa.Float(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['org_id'], ['organisations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fingerprints',
    sa.Column('hash', sa.BigInteger(), nullable=False),
    sa.Column('doc_id', sa.Integer(), nullable=False),
    sa.Column('pos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doc_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('hash', 'doc_id', 'pos')
    )
    op.create_index('ix_fingerprints_hash', 'fingerprints', ['hash'], unique=False)
    op.create_table('check_sources',
    sa.Column('check_id', sa.Integer(), nullable=False),
    sa.Column('source_doc_id', sa.Integer(), nullable=False),
    sa.Column('percent', sa.Float(), nullable=False),
    sa.Column('passages', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['check_id'], ['checks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_doc_id'], ['documents.id'], ),
    sa.PrimaryKeyConstraint('check_id', 'source_doc_id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('check_sources')
    op.drop_index('ix_fingerprints_hash', table_name='fingerprints')
    op.drop_table('fingerprints')
    op.drop_table('checks')
    op.drop_table('memberships')
    op.drop_index('ix_documents_text_hash', table_name='documents')
    op.drop_index('ix_documents_org_kind', table_name='documents')
    op.drop_table('documents')
    op.drop_table('users')
    op.drop_table('organisations')
    # ### end Alembic commands ###
